baseurl = "https://ksblog.netlify.com/"
languageCode = "en-us"
title = "Kori's Data Science Blog"
# Define how many pages appear per site
paginate = 2
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = ""
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Kori Sidwell"
    site_description = "Student // Athlete"
    location = "Erie, PA"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Kori's Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""


